// Generated by js_of_ocaml 2.8.1
(function(p){"use strict";var
U=500,T="Sys_error",ae=224,ad="Invalid_argument",n=1024,S=57343,ac=512,ab="End_of_file",aa="Failure",R="Undefined_recursive_module",$="Stack_overflow",d=128,c="",z=" : file already exists",O=2048,P=56320,Q=240,q=100,b=248,_="Not_found",M="Assert_failure",N="/",Y="Sys_blocked_io",Z="fd ",L="Out_of_memory",X="Match_failure",W="Division_by_zero",V=1e3,aI=0;function
l(){return aI++}function
aj(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aS(g){for(var
h=c,b=h,a,j,e=0,i=g.length;e<i;e++){a=g.charCodeAt(e);if(a<d){for(var
f=e+1;f<i&&(a=g.charCodeAt(f))<d;f++);if(f-e>ac){b.substr(0,1);h+=b;b=c;h+=g.slice(e,f)}else
b+=g.slice(e,f);if(f==i)break;e=f}if(a<O){b+=String.fromCharCode(192|a>>6);b+=String.fromCharCode(d|a&63)}else
if(a<55296||a>=S)b+=String.fromCharCode(ae|a>>12,d|a>>6&63,d|a&63);else
if(a>=56319||e+1==i||(j=g.charCodeAt(e+1))<P||j>S)b+="\xef\xbf\xbd";else{e++;a=(a<<10)+j-56613888;b+=String.fromCharCode(Q|a>>18,d|a>>12&63,d|a>>6&63,d|a&63)}if(b.length>n){b.substr(0,1);h+=b;b=c}}return h+b}function
aM(b,a){if(a.repeat)return a.repeat(b);var
d=c,e=0;if(b==0)return d;for(;;){if(b&1)d+=a;b>>=1;if(b==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
aV(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
C(b,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==b.length)return e.apply(null,b);var
f=c;for(;0<a;d+=n,a-=n)f+=e.apply(null,aV(b,d,Math.min(a,n)));return f}function
ah(a){if(a.t==2)a.c+=aM(a.l-a.c.length,"\0");else
a.c=C(a.c,0,a.c.length);a.t=0}function
aR(g){for(var
l=c,e=c,i,h,j,a,b=0,k=g.length;b<k;b++){h=g.charCodeAt(b);if(h<d){for(var
f=b+1;f<k&&(h=g.charCodeAt(f))<d;f++);if(f-b>ac){e.substr(0,1);l+=e;e=c;l+=g.slice(b,f)}else
e+=g.slice(b,f);if(f==k)break;b=f}a=1;if(++b<k&&((j=g.charCodeAt(b))&-64)==d){i=j+(h<<6);if(h<ae){a=i-12416;if(a<d)a=1}else{a=2;if(++b<k&&((j=g.charCodeAt(b))&-64)==d){i=j+(i<<6);if(h<Q){a=i-925824;if(a<O||a>=55295&&a<57344)a=2}else{a=3;if(++b<k&&((j=g.charCodeAt(b))&-64)==d&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){b-=a;e+="\ufffd"}else
if(a>65535)e+=String.fromCharCode(55232+(a>>10),P+(a&1023));else
e+=String.fromCharCode(a);if(e.length>n){e.substr(0,1);l+=e;e=c}}return l+e}function
aQ(a){switch(a.t){case
9:return a.c;default:ah(a);case
0:if(aj(a.c)){a.t=9;return a.c}a.t=8;case
8:return aR(a.c)}}function
h(c,a,b){this.t=c;this.c=a;this.l=b}h.prototype.toString=function(){return aQ(this)};function
ak(a){var
b=9;if(!aj(a))b=8,a=aS(a);return new
h(b,a,a.length)}function
aJ(b,a){throw[0,b,a]}function
a(a){return new
h(0,a,a.length)}function
an(c,b){aJ(c,a(b))}var
e=[0];function
g(a){an(e.Sys_error,a)}function
aD(a){if(!a.opened)g("Cannot flush a closed channel");if(a.buffer==c)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=c;return 0}function
ai(a){an(e.Invalid_argument,a)}function
k(a){if(a<0)ai("String.create");return new
h(a?2:9,c,a)}var
ao=0;function
aW(){return new
Date().getTime()/V}function
D(){return Math.floor(aW())}function
i(b){this.data=b;this.inode=ao++;var
a=D();this.atime=a;this.mtime=a;this.ctime=a}i.prototype={truncate:function(){this.data=k(0);this.modified()},modified:function(){var
a=D();this.atime=a;this.mtime=a}};function
B(a){return a.l}function
am(a){a=a
instanceof
h?a.toString():a;g(a+": No such file or directory")}var
aB=N;function
r(a){a=a
instanceof
h?a.toString():a;if(a.charCodeAt(0)!=47)a=aB+a;var
e=a.split(N),b=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(c);break;default:b.push(e[d]);break}b.orig=a;return b}function
j(){this.content={};this.inode=ao++;var
a=D();this.atime=a;this.mtime=a;this.ctime=a}j.prototype={exists:function(a){return this.content[a]?1:0},mk:function(b,a){this.content[b]=a},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
t=new
j();t.mk(c,new
j());function
A(c){var
a=t;for(var
b=0;b<c.length;b++){if(!(a.exists&&a.exists(c[b])))am(c.orig);a=a.get(c[b])}return a}function
aP(b){var
c=r(b),a=A(c);return a
instanceof
j?1:0}function
aN(a){return new
h(4,a,a.length)}function
ag(b){if(p.Uint8Array)var
c=new(p.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
aX(a){if(a.t!=4)ag(a);return a.c}function
aC(l,c){var
e=r(l),b=t;for(var
f=0;f<e.length-1;f++){var
d=e[f];if(!b.exists(d))b.mk(d,new
j());b=b.get(d);if(!(b
instanceof
j))g(e.orig+z)}var
d=e[e.length-1];if(b.exists(d))g(e.orig+z);if(c
instanceof
j)b.mk(d,c);else
if(c
instanceof
i)b.mk(d,c);else
if(c
instanceof
h)b.mk(d,new
i(c));else
if(c
instanceof
Array)b.mk(d,new
i(aN(c)));else
if(c.toString){var
k=a(c.toString());b.mk(d,new
i(k))}else
ai("caml_fs_register");return 0}function
aO(f){var
a=t,c=r(f),d,e;for(var
b=0;b<c.length;b++){if(a.auto){d=a.auto;e=b}if(!(a.exists&&a.exists(c[b])))return d?d(c,e):0;a=a.get(c[b])}return 1}function
o(c,d,a){if(e.fds===undefined)e.fds=new
Array();a=a?a:{};var
b={};b.file=d;b.offset=a.append?B(d.data):0;b.flags=a;e.fds[c]=b;e.fd_last_idx=c;return c}function
aY(b,d,j){var
a={};while(d){switch(d[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}d=d[2]}var
f=b.toString(),i=r(b);if(a.rdonly&&a.wronly)g(f+" : flags Open_rdonly and Open_wronly are not compatible");if(a.text&&a.binary)g(f+" : flags Open_text and Open_binary are not compatible");if(aO(b)){if(aP(b))g(f+" : is a directory");if(a.create&&a.excl)g(f+z);var
h=e.fd_last_idx?e.fd_last_idx:0,c=A(i);if(a.truncate)c.truncate();return o(h+1,c,a)}else
if(a.create){var
h=e.fd_last_idx?e.fd_last_idx:0;aC(b,k(0));var
c=A(i);return o(h+1,c,a)}else
am(b)}o(0,new
i(k(0)));o(1,new
i(k(0)));o(2,new
i(k(0)));function
aE(b){var
a=e.fds[b];if(a.flags.wronly)g(Z+b+" is writeonly");return{file:a.file,offset:a.offset,fd:b,opened:true,refill:null}}function
af(d,e,a,f,c){if(c==0)return 0;if(f==0&&(c>=a.l||a.t==2&&c>=a.c.length)){a.c=d.t==4?C(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);a.t=a.c.length==a.l?0:2}else
if(a.t==2&&f==a.c.length){a.c+=d.t==4?C(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);a.t=a.c.length==a.l?0:2}else{if(a.t!=4)ag(a);var
g=d.c,h=a.c;if(d.t==4)for(var
b=0;b<c;b++)h[f+b]=g[e+b];else{var
i=Math.min(c,g.length-e);for(var
b=0;b<i;b++)h[f+b]=g.charCodeAt(e+b);for(;b<c;b++)h[f+b]=0}}return 0}function
aT(a){var
b=p;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
aU(a){var
b=p;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}var
s=new
Array();function
aL(b,h){var
g=a(h),c=B(g),f=B(b.file.data),e=b.offset;if(e+c>=f){var
d=k(e+c);af(b.file.data,0,d,0,f);af(g,0,d,e,c);b.file.data=d}b.offset+=c;b.file.modified();return 0}function
al(a){var
b;switch(a){case
1:b=aU;break;case
2:b=aT;break;default:b=aL}var
f=e.fds[a];if(f.flags.rdonly)g(Z+a+" is readonly");var
d={file:f.file,offset:f.offset,fd:a,opened:true,buffer:c,output:b};s[d.fd]=d;return d}function
aF(){var
a=0;for(var
b
in
s)if(s[b].opened)a=[0,s[b],a];return a}function
aH(a){return a
instanceof
Array?a[0]:a
instanceof
h?252:V}function
f(c,b,a){e[c+1]=b;if(a)e[a]=b}var
aG={};function
aA(a){if((a.t&6)!=0)ah(a);return a.c}function
aK(a,b){aG[aA(a)]=b;return 0}var
E=[b,a(M),-11];f(11,[b,a(R),-12],R);f(10,E,M);f(9,[b,a(Y),-10],Y);f(8,[b,a($),-9],$);f(7,[b,a(X),-8],X);f(6,[b,a(_),-7],_);f(5,[b,a(W),-6],W);f(4,[b,a(ab),-5],ab);f(3,[b,a(ad),-4],ad);f(2,[b,a(aa),-3],aa);f(1,[b,a(T),-2],T);f(0,[b,a(L),-1],L);l(0);aE(0);al(1);al(2);l(0);l(0);l(0);var
F=[0,0],at=a("Js.Error"),ay=a("canvas"),av=a("img"),aw=a("Dom_html.Canvas_not_available"),az=[0,a("v.ml"),53,17];function
G(a){F[1]=[0,a,F[1]];return 0}var
u=p,H=null,as=u.Array,I=[b,at,l(0)],v=[0,I,{}],ar=undefined,aq=aH(v)===b?v:v[1];aK(a("jsError"),aq);(function(a){throw a});G(function(a){return a[1]===I?[0,ak(a[2].toString())]:0});G(function(a){return a
instanceof
as?0:[0,ak(a.toString())]});function
J(b,a){b.appendChild(a);return 0}var
au="2d";function
K(b,a){return b.createElement(a.toString())}var
ax=[b,aw,l(0)];u.HTMLElement===ar;var
x=u.document,m=K(x,ay);if(1-(m.getContext==H?1:0)){m.width=U;m.height=U;var
w=K(x,av);w.src="coin-sprite-animation.png";m.getContext(au).drawImage(w,0,0,q,q,0,0,q,q);var
y=x.getElementById("body");if(y==H)throw[0,E,az];J(y,m);J(y,w);var
ap=function(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{aD(d)}catch(a){}var
a=c;continue}return 0}};ap(aF(0));return}throw ax}(function(){return this}()));
