#!/bin/bash

# If no arguments are supplied, display Cml help
if [[ $# == 0 ]]; then
  /usr/local/bin/cml.byte "--help"

# If arguments are supplied, pass them to cml bytecode program. Up to 5 args allowed.
else
  /usr/local/bin/cml.byte $1 $2 $3 $4 $5

  exit 64
fi
